{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dropbot-chip-qc
  version: {{ GIT_VERSION }}

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - dropbot-chip-qc = dropbot_chip_qc.bin.test:main

requirements:
  build:
    - blinker
    - opencv
    - pandas
    - pyzbar
    - trollius

  run:
    - blinker
    - opencv
    - pandas
    - pyzbar
    - trollius

test:
  imports:
    - dropbot_chip_qc

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
