{% if GIT_DESCRIBE_NUMBER > '0' %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dropbot-chip-qc
  version: {{ GIT_VERSION }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - dropbot-chip-qc = dropbot_chip_qc.bin.test:main
  skip: true  # [not win]

requirements:
  build:
    - pip
    - python

  run:
    - asyncio-helpers
    - blinker
    - dmf-chip >=0.5.0
    - dropbot >=1.74.0,<2.0.0
    - dropbot-monitor
    - functools32
    - ipywidgets
    - jinja2
    - json-tricks
    - logging-helpers
    - lxml
    - matplotlib
    - mutagen
    - networkx
    - opencv
    - pandas
    - path_helpers
    - pillow
    - pyside2
    - pywin32
    - pyzbar
    - qrcode
    - si-prefix
    - svg-model
    - trollius

test:
  imports:
    - dropbot_chip_qc
    - dropbot_chip_qc.async
    - dropbot_chip_qc.video
    - dropbot_chip_qc.bin.test
    - dropbot_chip_qc.bin.video
    - qrcode.image.pil

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
