{% if GIT_DESCRIBE_NUMBER %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] + '.post' + GIT_DESCRIBE_NUMBER %}
{% else %}
{% set GIT_VERSION = GIT_DESCRIBE_TAG[1:] %}
{% endif %}
# source will be downloaded prior to filling in jinja templates
# Example assumes that this folder has setup.py in it
source:
  git_url: ../

package:
  name: dropbot-chip-qc
  version: {{ GIT_VERSION }}

build:
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - dropbot-chip-qc = dropbot_chip_qc.bin.test:main
  skip: true  # [not win]

requirements:
  build:
    - asyncio-helpers
    - blinker
    - dropbot >=2.1.1
    - functools32
    - lxml
    - mutagen
    - networkx
    - opencv
    - pandas
    - pillow
    - pyside2
    - pywin32
    - pyzbar
    - qrcode
    - trollius

  run:
    - asyncio-helpers
    - blinker
    - dropbot >=2.1.1
    - functools32
    - lxml
    - mutagen
    - networkx
    - opencv
    - pandas
    - pillow
    - pyside2
    - pywin32
    - pyzbar
    - qrcode
    - trollius

test:
  imports:
    - dropbot_chip_qc
    - dropbot_chip_qc.async
    - dropbot_chip_qc.video
    - dropbot_chip_qc.bin.test
    - dropbot_chip_qc.bin.video

about:
  home: https://github.com/sci-bots/{{ PKG_NAME }}
  license: BSD
